from __future__ import annotations

# Truncation limits (chars)
RAW_TEXT_MAX_CHARS = 8000
RAW_SECTION_MAX_CHARS = 4000
LOG_EXCERPT_MAX_CHARS = 500

# Warning codes
WARN_TEXT_EMPTY = 'TEXT_EMPTY'
WARN_TEXT_TOO_SHORT = 'TEXT_TOO_SHORT'
WARN_SECTION_NONE_FOUND = 'SECTION_NONE_FOUND'
WARN_SECTION_OVERLAP_SUSPECTED = 'SECTION_OVERLAP_SUSPECTED'
WARN_SKILLS_FROM_NON_SKILLS_SECTION = 'SKILLS_FROM_NON_SKILLS_SECTION'
WARN_PARSER_FALLBACK_USED = 'PARSER_FALLBACK_USED'
WARN_EXTRACTION_FAILED = 'EXTRACTION_FAILED'
WARN_EMBEDDINGS_FAILED = 'EMBEDDINGS_FAILED'

